services:
  web:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # Email settings (using Gmail as an example)
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=your-email@gmail.com
      - EMAIL_HOST_PASSWORD=your-app-password
